# id: 1
server:
  address: "admin:12345"

loop-period: 
  post: "100ns"
  comment: "100ns"

files-path:
  post: "./files/posts_small.csv"
  comment: "./files/comments_small.csv"
  sentiment-meme: "./files/sentiment_meme"
  school-memes: "./files/school_memes"

log:
  level: "info"